### ISSUE TITLE
侧边垂直滑动问题

### ISSUE THREAD

**Issue by YuanLiou** [YoKeyword/SwipeBackFragment#1]
你好，最近发现了这个 Library 。
实作的过程之中发现接近垂直的滑动侧边部分，会造成快速的返回。

![ezgif-4226145478](https://cloud.githubusercontent.com/assets/4803452/16223993/ac4cebec-37d2-11e6-8137-123cf0276457.gif)

**Comment by YoKeyword** [comment]
@YuanLiou 感谢你的反馈，这个是ViewDragHelper的边缘滑动的特性，参考官方的侧滑抽屉栏，一般来说用户是不会这样误操作的；如果你需要改良的话，你可能需要修改其源码 :)

**Comment by YuanLiou** [comment]
@YoKeyword 你好，原来是这样。
刚刚试着把这 Library 加入整个 View 都能 Swipe Back 的功能，才发现了这个问题。这样子看起来这个方法似乎不适合整个画面都能 Swipe Back 阿。🤔

**Comment by YoKeyword** [comment]
@YuanLiou 整个都可以滑动返回的交互方式现在比较少，而且不少情况会和其它手势冲突，所以就没有支持，后续有时间的话考虑加上；目前你可以自己修改下代码，来达到你的需求哈  :)

**Comment by YuanLiou** [comment]
好的，谢谢。 :)
