### ISSUE TITLE
ToolBar的返回按钮点击直接退出了

### ISSUE THREAD

**Issue by iboying** [YoKeyword/SwipeBackFragment#2]
使用SwipeBackFragment，滑动可以正常返回上一次，点击ToolBar的按钮后直接就退出了，我是从HomeFragment进入到的OrderCheckFragment，从`OrderCheckFragment` 点击实现返回
1、栈层级
![image](https://cloud.githubusercontent.com/assets/10523771/16581620/0a04c7f4-42dd-11e6-9e51-39dc846f7f27.png)
2、如你所见，会多出个SupportRequestManagerFragment，查了一下，是Glide图片加载库生成的，我就怀疑点击Toolbar返回按钮返回到SupportRequestManagerFragment了，所以出现问题，但是滑动却可以正常返回，看了会源码，还是没解决好，只能来问作者啦，多谢多谢

**Comment by YoKeyword** [comment]
Toolbar的返回事件，你是如何写的呢？

Glide的那个Fragment不必太在意 你只要pop当前的Fragment 就会显示到上一个Fragment了

**Comment by iboying** [comment]
恩  是的，是我的Toolbar的返回逻辑没有调用pop()，项目之前自己管理fragment， 现在使用了fragmentation，爽的不是一点点，支持作者

**Comment by YoKeyword** [comment]
@iboying OK ，多参考下demo里的3种架构  ，看自己属于哪种架构。  感谢支持 🙏
