### ISSUE TITLE
MyFragment extends SwipeBackFragment ,and then  when swipeback ,MyFragment did not call onDestroyView()

### ISSUE THREAD

**Issue by MartinLi2015** [YoKeyword/SwipeBackFragment#3]
So after swipeback to upper,I couldn't touch or click anywhere until I click the backButton

**Comment by YoKeyword** [comment]
Can you provide a snippet of your code ?

**Comment by MartinLi2015** [comment]
This happens when I closed MyFragment by myself

![Uploading image.png…]()

**Comment by MartinLi2015** [comment]
public void onBackPressed() {

//        getActivity().getSupportFragmentManager().beginTransaction()
//                .setCustomAnimations(R.anim.fragment_slide_right_enter,R.anim.fragment_slide_right_exit)
//                .detach(this).commit();
        getActivity().getSupportFragmentManager().popBackStackImmediate();
    }
Maybe It is  my fault

**Comment by YoKeyword** [comment]
You can refer to the DEMO. 
Or you are Chinese...   ＝。＝    My QQ: 328903522
