### ISSUE TITLE
通过viewpager加载起来的fragment，然后start启动其他fragment，侧滑返回划过看见下面的页面是空白的

### ISSUE THREAD

**Issue by qinyang1018** [YoKeyword/SwipeBackFragment#5]
![qq20161108-0](https://cloud.githubusercontent.com/assets/15726024/20086261/d95efb8a-a5a9-11e6-8298-03ebfe31bb17.png)

**Comment by YoKeyword** [comment]
层级对不对呢

ViewPager里的子FG要避免直接start的  需要getParent.start 避免层级失控

**Comment by qinyang1018** [comment]
viewpager里面的fragment无法直接启动下一层级的fragment，直接启动会白屏，我是用rxbus通过viewpager所属的fragment启动的

**Comment by YoKeyword** [comment]
你在用Fragmentation库吗？  要不你看下启动的第二个demo，有类似场景：
![screenshot_20161108-134945](https://cloud.githubusercontent.com/assets/9691640/20088511/6bf7a04e-a5bb-11e6-9095-104f72c3e212.png)

**Comment by qinyang1018** [comment]
在用的  好的 我看下  麻烦您了

**Comment by xyxzfj** [comment]
同样遇到这一问题。滑动返回时底部的Fragment是灰色的，滑动返回完成后才显示。
添加Fragment的时候是先hide()后add()。不hide()就没问题（但不hide()会导致Fragment无法接收到onHiddenChanged()回调，项目依赖它）。求解。

**Comment by YoKeyword** [comment]
@xyxzfj 
你可以在[SwipeBackLayout的327行](https://github.com/YoKeyword/SwipeBackFragment/blob/master/swipeback/src/main/java/me/yokeyword/swipebackfragment/SwipeBackLayout.java#L327)处打断点，观察mPreFragment～

**Comment by xyxzfj** [comment]
@YoKeyword 感谢回复！
gh下图是我打日志的结果：
<img width="1440" alt="screen shot 2016-12-26 at 15 43 54" src="https://cloud.githubusercontent.com/assets/1221283/21478006/4e6a5070-cb82-11e6-8899-010c67fd117c.png">
第二、三次开始滑时，preView已经是VISIBLE了的，但滑动过程中，背景仍然是灰色的，滑动返回之后才显示上一个Fragment。

**Comment by qinyang1018** [comment]
@xyxzfj 我当时的问题是因为层级的关系  你可以看下堆栈信息 是不是层级不对

**Comment by xyxzfj** [comment]
@YoKeyword @qinyang1018 看了下Layout树。是前一个SwipeBackLayout被hidden了。原因待查。
<img width="1440" alt="screen shot 2016-12-26 at 15 56 39" src="https://cloud.githubusercontent.com/assets/1221283/21478213/151b65d2-cb84-11e6-9918-26352380eb50.png">

**Comment by qinyang1018** [comment]
@xyxzfj 抱歉  过年这段时间一直没上网， 看你对这个位置有些研究方便留个联系加下QQ吗？ 我的QQ：8400074    

我现在还有个问题需要处理  就是从activity启动另一个activity，然后从新启动的activity中loadRootFragment一个fragment这时候滑动返回这个fragment时候背景是全黑色的，因为当前fragment所在的activity是没有布局只loadfragment用的所以是黑色的。     

这种情况确实是我设计的问题  但是现在不得不activity和fragment混合使用。

我现在是在stytle中通过<item name="android:windowIsTranslucent">true</item>去让activity透明来解决的，但是使用这个办法混引起跳转抖动，activity透明导致的跳转看见桌面和点击穿透等问题。  
不知道  你有什么更好的办法没？

**Comment by qinyang1018** [comment]
我现在能找到目前还没有发现问题的解决办法就是单独给需要的activity设置透明
