### ISSUE TITLE
右滑看见桌面

### ISSUE THREAD

**Issue by Saqrag** [YoKeyword/SwipeBackFragment#6]
Saqrag：
我在小米4c android5.1系统上试过，正常。但是在红米2 android4.4系统上测试，从一个Activity推出到上一个Activity，右滑时下面看到手机桌面，右滑结束回到上一个activity。这个怎么解决？ 感谢

YoKeyword：
上一个Activity内的布局填充个颜色看看， SwipeActivity这块是参照开源库SwipeBackLayout 你检查下是否使用上的细节有问题
     
Saqrag：
你好，我在4.0以上的设备上基本都试过，只有4.4.4设备由此问题。而且只有Activity有问题，Fragment没有问题。我估计是动画的原因，在4.4.4设备从一个Activity返回到上一个Activity时,上一个Activity有返回动画。而这动画是从屏幕外流入到屏幕。所以右滑的时候上一个Activity在屏幕外头。因为Fragment没有返回动画所以不影响。 但是我在网上找了很多方法就是禁不了4.4.4设备地动画。

YoKeyword：
我之前也测过红米4.4当时是正常的，我刚也试了一台红米4.4，是正常的；
你在Demo里的FirstSwipeBackFragment这个类里的onClick()方法里替换成：
startActivity(new Intent(_mActivity, SwipeBackSampleActivity.class));
然后在第一个Demo里抽屉菜单里选择打开"SwipeBackActivity+Fragment"菜单，然后点击界面再打开一个SwipeBackSampleActivity，然后侧滑看看～
     
Saqrag：
不好意思，我当初引用的是SwipeBackFragment库，在浏览的时候问错地方了。我刚刚用您的方法试了一下Fragmentation库没有问题。然后试了一下SwipeBackFragment库，在Demo的FirstSwipeBackFragment的onClick()方法中分别调用startActivity(new Intent(_mActivity, MainActivity.class))和startActivity(new Intent(_mActivity, TestActivity.class)),TestActivity时我建的测试Activity,均有上述问题

**Comment by YoKeyword** [comment]
是的 确实存在这个问题 [SwipeBackLayout那个库里也有这个issue](https://github.com/ikew0ng/SwipeBackLayout/issues/108) 

不过解决办法也很简单，给Activity设置一个自定动画即可，比如：
````java
overridePendingTransition(R.anim.h_fragment_enter, R.anim.h_fragment_exit);
````

**Comment by Saqrag** [comment]
解决了，多谢！ 根部Activity的theme设置为windowIsTranslucent=false。再次感谢

**Comment by xsslong** [comment]
用您提供的办法解决了, 太感谢了
